server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
    session:
      cookie:
        http-only: true
        secure: false
      timeout: 30m

spring:
  application:
    name: moyun-reading-platform

  # TiDB云数据库配置
  datasource:
    url: jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/MoYun?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true&requireSSL=false&verifyServerCertificate=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 2S6V11ZeEkmKd4c.root
    password: slSfRyXikW7cdDkp
    # HikariCP连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 3000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
    
  # JPA配置（适配TiDB）
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    
  # H2控制台配置（已禁用，使用TiDB）
  h2:
    console:
      enabled: false
      path: /h2-console
      
  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 日志配置
logging:
  level:
    com.moyun.reading: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 自定义配置
moyun:
  jwt:
    secret: moyun-reading-platform-jwt-secret-key-2024
    expiration: 86400000 # 24小时
  upload:
    path: uploads/
    avatar-path: uploads/avatars/
    book-cover-path: uploads/books/

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/moyun_reading?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:moyun}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    com.moyun.reading: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN 